default_platform(:android)

platform :android do
  desc "Lane for android firbase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor prod --target lib/main_prod.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:699411488492:android:7656bef2b5807e7b0d4fc9",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
      testers: "ammaralkady987654@gmail.com , walidtawfik362@gmail.com, mazen.mohamed1393@gmail.com",
      release_notes: "- ..."
    )
  end
end
